# Generated by Django 4.2.9 on 2026-05-08 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyMast',
            fields=[
                ('CompanyId', models.IntegerField(primary_key=True, serialize=False)),
                ('Company', models.TextField()),
                ('Address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DepartMast',
            fields=[
                ('DepartId', models.IntegerField(primary_key=True, serialize=False)),
                ('DepartName', models.TextField(blank=True, null=True)),
                ('Status', models.TextField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='DesMast',
            fields=[
                ('Desgid', models.IntegerField(primary_key=True, serialize=False)),
                ('Designation', models.TextField()),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.departmast')),
            ],
        ),
        migrations.CreateModel(
            name='GatePass',
            fields=[
                ('allowing_entry', models.CharField(choices=[('Yes', 'Hazardous Area'), ('No', 'Non Hazardous Area')], max_length=10)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('cardNo', models.CharField(max_length=250)),
                ('date', models.DateField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('company', models.CharField(blank=True, max_length=250, null=True)),
                ('address', models.CharField(blank=True, max_length=250, null=True)),
                ('mobile', models.CharField(blank=True, max_length=250, null=True)),
                ('vehicleNo', models.CharField(blank=True, max_length=250, null=True)),
                ('purpose', models.TextField()),
                ('visitor_name', models.TextField()),
                ('noOfPerson', models.CharField(blank=True, max_length=250, null=True)),
                ('idNo', models.CharField(blank=True, max_length=250, null=True)),
                ('typeOf', models.CharField(blank=True, max_length=250, null=True)),
                ('govt_id', models.CharField(blank=True, max_length=250, null=True)),
                ('govtno', models.CharField(blank=True, max_length=250, null=True)),
                ('personToMeet', models.CharField(blank=True, max_length=250, null=True)),
                ('inTime', models.CharField(blank=True, max_length=250, null=True)),
                ('outTime', models.CharField(blank=True, max_length=250, null=True)),
                ('permittedBy', models.CharField(blank=True, max_length=250, null=True)),
                ('carringGadget', models.CharField(blank=True, max_length=250, null=True)),
                ('passNo', models.CharField(blank=True, max_length=250, null=True)),
                ('image', models.ImageField(default='default.jpg', upload_to='gatepass_images/')),
                ('remarks', models.TextField(blank=True, null=True)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('renew_remarks', models.TextField(blank=True, max_length=250, null=True)),
                ('createdAt', models.DateField(blank=True, null=True)),
                ('updatedAt', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='true', max_length=250)),
            ],
            options={
                'db_table': 'GatePass',
            },
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MachineMast',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('MachineNo', models.CharField(max_length=50)),
                ('RDRNO', models.CharField(max_length=50)),
                ('PortNo', models.CharField(max_length=50)),
                ('Password', models.CharField(max_length=100)),
                ('con_status', models.CharField(max_length=50)),
                ('Site', models.CharField(max_length=50)),
                ('MachineType', models.TextField()),
                ('SRNO', models.CharField(max_length=100, unique=True)),
                ('RDRNAME', models.TextField()),
                ('IPAddress', models.TextField()),
                ('IO', models.CharField(max_length=50)),
                ('LastConnected', models.DateTimeField(blank=True, null=True)),
                ('Response', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Machines',
            },
        ),
        migrations.CreateModel(
            name='MonitorData',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('SRNO', models.CharField(max_length=50)),
                ('EnrollID', models.CharField(max_length=100)),
                ('PunchDate', models.DateTimeField()),
                ('TRID', models.CharField(max_length=50)),
                ('SEND_SERVER', models.CharField(blank=True, max_length=50, null=True)),
                ('RESEND_SERVER', models.CharField(blank=True, max_length=50, null=True)),
                ('Errorstatus', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'MonitorDataTbl',
            },
        ),
        migrations.CreateModel(
            name='ReportLog',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('addedon', models.DateTimeField(auto_now_add=True, null=True)),
                ('Status', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='EnrollMast',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('enrollid', models.CharField(max_length=100, unique=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.departmast')),
            ],
            options={
                'db_table': 'EnrollMast',
            },
        ),
        migrations.CreateModel(
            name='EmpMast',
            fields=[
                ('ids', models.BigAutoField(primary_key=True, serialize=False)),
                ('empcode', models.CharField(max_length=100)),
                ('Cardno', models.CharField(max_length=50)),
                ('Name', models.TextField(blank=True, null=True)),
                ('Cardstatus', models.BooleanField(default=True)),
                ('Shift', models.CharField(max_length=50)),
                ('CatName', models.TextField(blank=True, null=True)),
                ('STATUS_E', models.CharField(blank=True, max_length=50, null=True)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.companymast')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.departmast')),
                ('designation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.desmast')),
                ('enrollid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.enrollmast')),
            ],
            options={
                'db_table': 'EmpMast',
            },
        ),
    ]
