# Generated by Django 4.2.9 on 2024-05-19 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceConTbl',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('con_date', models.DateTimeField()),
                ('SRNO', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Machines',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('IPAddress', models.CharField(max_length=200)),
                ('PortNo', models.CharField(max_length=50)),
                ('Password', models.CharField(max_length=200)),
                ('MachineType', models.CharField(max_length=100)),
                ('con_status', models.TextField()),
                ('Site', models.BigIntegerField()),
                ('IO', models.IntegerField()),
                ('RDRNO', models.IntegerField()),
                ('RDRNAME', models.TextField()),
                ('SRNO', models.CharField(max_length=100)),
                ('LastConnected', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='MonitorDataTbl',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('SRNO', models.CharField(max_length=50)),
                ('EnrollID', models.CharField(max_length=50)),
                ('PunchDate', models.DateTimeField()),
                ('TRID', models.IntegerField()),
                ('SEND_SERVER', models.CharField(max_length=50)),
                ('RESEND_SERVER', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='MasterDepart',
        ),
    ]
