# Generated by Django 4.2.9 on 2026-05-15 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitordata',
            name='Errorstatus',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
