# Generated by Django 4.2.9 on 2024-05-19 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_devicecontbl_machines_monitordatatbl_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyMast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CompanyId', models.IntegerField()),
                ('Company', models.TextField()),
                ('Address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DepartMast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DepartId', models.IntegerField()),
                ('DepartName', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DesMast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Desgid', models.IntegerField()),
                ('Designation', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='EmpMast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Empcode', models.BigIntegerField()),
                ('CompName', models.TextField()),
                ('Cardno', models.CharField(max_length=50)),
                ('Name', models.TextField()),
                ('Deptid', models.IntegerField()),
                ('Catid', models.IntegerField()),
                ('Compid', models.IntegerField()),
                ('Desgid', models.IntegerField()),
                ('Cardstatus', models.TextField()),
                ('Shift', models.CharField(max_length=50)),
                ('CatName', models.TextField()),
                ('STATUS_E', models.CharField(max_length=50)),
            ],
        ),
    ]
