# Generated by Django 4.2.9 on 2024-06-13 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_machines_machineno'),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineMast',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('SRNO', models.TextField()),
                ('Name', models.TextField()),
                ('Response', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MonitorData',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('SRNO', models.CharField(max_length=50)),
                ('EnrollID', models.CharField(max_length=50)),
                ('PunchDate', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='DeviceConTbl',
        ),
        migrations.DeleteModel(
            name='Machines',
        ),
        migrations.DeleteModel(
            name='MonitorDataTbl',
        ),
        migrations.RemoveField(
            model_name='companymast',
            name='id',
        ),
        migrations.RemoveField(
            model_name='departmast',
            name='id',
        ),
        migrations.RemoveField(
            model_name='desmast',
            name='id',
        ),
        migrations.RemoveField(
            model_name='empmast',
            name='Catid',
        ),
        migrations.RemoveField(
            model_name='empmast',
            name='CompName',
        ),
        migrations.RemoveField(
            model_name='empmast',
            name='Compid',
        ),
        migrations.RemoveField(
            model_name='empmast',
            name='Deptid',
        ),
        migrations.RemoveField(
            model_name='empmast',
            name='Desgid',
        ),
        migrations.RemoveField(
            model_name='empmast',
            name='id',
        ),
        migrations.AddField(
            model_name='departmast',
            name='Status',
            field=models.TextField(default=True),
        ),
        migrations.AddField(
            model_name='desmast',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.departmast'),
        ),
        migrations.AddField(
            model_name='empmast',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.companymast'),
        ),
        migrations.AddField(
            model_name='empmast',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.departmast'),
        ),
        migrations.AddField(
            model_name='empmast',
            name='designation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.desmast'),
        ),
        migrations.AddField(
            model_name='empmast',
            name='ids',
            field=models.BigIntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='companymast',
            name='CompanyId',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='departmast',
            name='DepartId',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='departmast',
            name='DepartName',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='desmast',
            name='Desgid',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='empmast',
            name='Cardstatus',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='empmast',
            name='CatName',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='empmast',
            name='Empcode',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='empmast',
            name='Name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='empmast',
            name='STATUS_E',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
