# Generated by Django 4.2.9 on 2024-06-13 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_machinemast_monitordata_delete_devicecontbl_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empmast',
            name='Empcode',
        ),
        migrations.AddField(
            model_name='empmast',
            name='empcode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.monitordata'),
        ),
    ]
