# Generated by Django 4.2.9 on 2024-06-13 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_empmast_empcode_empmast_empcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empmast',
            name='ids',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
