# Generated by Django 4.2.9 on 2024-06-14 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_machinemast_devicemodel_machinemast_machineno'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrollMast',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True)),
                ('from_status', models.CharField(max_length=100)),
                ('to_status', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='empmast',
            name='empcode',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='monitordata',
            name='EnrollID',
            field=models.CharField(max_length=100),
        ),
    ]
