# Generated by Django 4.2.9 on 2024-06-14 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_enrollmast_alter_empmast_empcode_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrollmast',
            old_name='from_status',
            new_name='empcode',
        ),
        migrations.RemoveField(
            model_name='enrollmast',
            name='name',
        ),
        migrations.RemoveField(
            model_name='enrollmast',
            name='to_status',
        ),
        migrations.AlterField(
            model_name='empmast',
            name='empcode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.enrollmast'),
        ),
    ]
