# Generated by Django 4.2.9 on 2024-06-15 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_rename_from_status_enrollmast_empcode_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrollmast',
            old_name='empcode',
            new_name='enrollid',
        ),
        migrations.AddField(
            model_name='empmast',
            name='enrollid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.enrollmast'),
        ),
        migrations.AlterField(
            model_name='empmast',
            name='empcode',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
