# Generated by Django 4.2.9 on 2024-06-18 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_rename_empcode_enrollmast_enrollid_empmast_enrollid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollmast',
            name='machine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.machinemast'),
        ),
    ]
