# Generated by Django 4.2.9 on 2024-06-19 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_enrollmast_machine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollmast',
            name='enrollid',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='monitordata',
            name='EnrollID',
            field=models.ForeignKey(db_column='EnrollID', on_delete=django.db.models.deletion.CASCADE, to='home.enrollmast', to_field='enrollid'),
        ),
    ]
