# Generated by Django 4.2.9 on 2024-06-20 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_enrollmast_enrollid_alter_monitordata_enrollid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitordata',
            name='EnrollID',
            field=models.CharField(max_length=100),
        ),
    ]
