# Generated by Django 4.2.9 on 2024-06-20 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_monitordata_enrollid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machinemast',
            name='SRNO',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='monitordata',
            name='EnrollID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.enrollmast'),
        ),
        migrations.AlterField(
            model_name='monitordata',
            name='SRNO',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.machinemast'),
        ),
    ]
