# Generated by Django 4.2.9 on 2024-06-20 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_machinemast_srno_alter_monitordata_enrollid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitordata',
            name='EnrollID',
            field=models.CharField(max_length=100),
        ),
    ]
