# Generated by Django 4.2.9 on 2024-06-20 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_monitordata_enrollid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitordata',
            name='SRNO',
            field=models.CharField(max_length=50),
        ),
    ]
