# Generated by Django 4.2.9 on 2024-06-20 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_remove_enrollmast_machine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machinemast',
            name='SRNO',
            field=models.TextField(),
        ),
    ]
