# Generated by Django 4.2.9 on 2024-06-20 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_alter_machinemast_srno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machinemast',
            name='SRNO',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
