# Generated by Django 4.2.9 on 2024-09-26 10:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_alter_machinemast_srno'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitordata',
            name='TRID',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
