# Generated by Django 4.2.9 on 2024-09-27 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_remove_monitordata_trid'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitordata',
            name='Errorstatus',
            field=models.BooleanField(default=True),
        ),
    ]
