# Generated by Django 4.2.9 on 2024-09-27 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_monitordata_errorstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollmast',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.departmast'),
        ),
    ]
