# Generated by Django 4.2.9 on 2024-10-03 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_enrollmast_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitordata',
            name='Errorstatus',
            field=models.BooleanField(default=False),
        ),
    ]
