# Generated by Django 2.1.15 on 2024-12-06 11:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_alter_monitordata_errorstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitordata',
            name='TRID',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
