# Generated by Django 4.2.9 on 2025-05-24 12:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_gatepass_reportlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='gatepass',
            name='visitor_name',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
